services:
  api1:
    image: renanofugi/rinha2026-deteccao-fraude:v11
    pull_policy: always
    environment:
      RINHA_UDS_PATH: /sockets/api1.sock
      RINHA_IVF_MAX_PROBES: "256"
      RINHA_IVF_PRUNE_MARGIN: "1.0"
      RINHA_HTTP_WORKERS: "1"
    volumes:
      - api-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "165MB"

  api2:
    image: renanofugi/rinha2026-deteccao-fraude:v11
    pull_policy: always
    environment:
      RINHA_UDS_PATH: /sockets/api2.sock
      RINHA_IVF_MAX_PROBES: "256"
      RINHA_IVF_PRUNE_MARGIN: "1.0"
      RINHA_HTTP_WORKERS: "1"
    volumes:
      - api-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "165MB"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - api-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.06"
          memory: "20MB"

volumes:
  api-sockets:
